### ISSUE TITLE
Java ?

### ISSUE THREAD

**Issue by giardb** [AzimutGoogleHashCode2017/HashCode2017#1]
Hi,

I have just look into your code and it seems to be written in java ?!? Is it a feature or an error? If it is an error, maybe you should try this https://www.python.org/ or this https://ocaml.org/index.fr.html. They seems more efficient than your solution.

**Comment by quentin-sommer** [comment]
Hi, I have a working solution here : https://github.com/quentin-sommer/hashcode2k17 feel free to fork it and claim it yours I won't tell you were using Java
